# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'emergencySituation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for emergencySituation
  pod 'NMapsMap'	
 

  target 'emergencySituationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'emergencySituationUITests' do
    # Pods for testing
  end

end
